In [2]:
"4 Lists"

'4 Lists'

In [3]:
lst = [10,20,30,'John',50,'Joe']
print("Elements of the List:\n")
print('\n'.join(map(str, lst)))

Elements of the List:

10
20
30
John
50
Joe


In [5]:
def Reverse(lst):
    return [ele for ele in reversed(lst)]
lst = [10, 11, 12, 13, 14, 15]
print(Reverse(lst))

[15, 14, 13, 12, 11, 10]


In [6]:
def findLength(string):
    count = 0
    for i in string:
        count+= 1
    return count
string = "geeksforgeeks"
print(findLength(string))

13


In [8]:
listOfStrings1 = ['Hi'] * 5
print(listOfStrings1)


['Hi', 'Hi', 'Hi', 'Hi', 'Hi']


In [13]:
a = 0
b = a
b = 1
print(a)
# a is not changed


0


In [20]:
a = [[]] * 3  # below is the difference
b = [[] for _ in xrange(3)] #the square brackets to create lists using this method

NameError: name 'xrange' is not defined

In [24]:
l1 = [1,2,3] * 3
print(l1)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [25]:
n=int(input("Enter the number till you want to check: "))
primes = []
for i in range (2, n+1):
    for j in range(2, i):
        if i%j == 0:
            break
    else:
        primes.append(i)
print(primes)

Enter the number till you want to check:  10


[2, 3, 5, 7]


In [28]:
number_list = [ x for x in range(10) ]
print(number_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [29]:
number_list = [ x for x in range(10) ]
print(number_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
def power_of_two(number):
    return number ** 2
worst_way_to_get_a_list_ever = list(map(power_of_two, numbers))

In [31]:
def flatten_list(_2d_list):
    flat_list = []
    # Iterate through the outer list
    for element in _2d_list:
        if type(element) is list:
            # If the element is of type list, iterate through the sublist
            for item in element:
                flat_list.append(item)
        else:
            flat_list.append(element)
    return flat_list

nested_list = [[1, 2, 3, 4], [5, 6, 7], [8, 9, 10]]
print('Original List', nested_list)
print('Transformed Flat List', flatten_list(nested_list))

Original List [[1, 2, 3, 4], [5, 6, 7], [8, 9, 10]]
Transformed Flat List [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [37]:
a_list = ["a_string", "the_longest_string", "string"]
longest_string = max(a_list, key=len)
print(longest_string)

words = ["alpha","omega","up","down","over","under","purple","red","blue","green"]


max(words, key=len)
'purple'

the_longest_string


'purple'

In [45]:
def collatz_sequence(n):
    collatz_list=list() #list to store the values of sequence
    
    while (n!=1) :
        collatz_list.append(n) 
        #if n is even
        if (n%2==0) :
            n=n//2
        else:
          #if n is odd
            n=(3*n)+1
    collatz_list.append(1)  #print 1 in the end   
    l=len(collatz_list)

    print("The length of collatz sequence is", l)
    print("The sequence is :")
    for i in range(0,l):
      print(collatz_list[i])

#driver code  
collatz_sequence(11)

The length of collatz sequence is 15
The sequence is :
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1


In [46]:
"5 Tuples"

'5 Tuples'

In [47]:
x = 5
y = 10

temp = x
x = y
y = temp

print('The value of x after swapping: {}'.format(x))
print('The value of y after swapping: {}'.format(y))

The value of x after swapping: 10
The value of y after swapping: 5


In [51]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica")

x = zip(a,b)

print(tuple(x))

(('John', 'Jenny'), ('Charles', 'Christy'), ('Mike', 'Monica'))


In [52]:
import math

a = (2, 3, 6)
b = (5, 7, 1)

d = math.dist(a, b)

print(d)

7.0710678118654755


In [53]:
"6 Dictionaries"

'6 Dictionaries'

In [ ]:
a_dictionary = {"a": 1, "b": 2}
dictionary_items = a_dictionary.items()
for item in dictionary_items:
    print(item)

In [1]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.get("model")

print(x)

Mustang


In [2]:
import random
import string

# printing lowercase
letters = string.ascii_lowercase
print ( ''.join(random.choice(letters) for i in range(10)) )

# printing uppercase
letters = string.ascii_uppercase
print ( ''.join(random.choice(letters) for i in range(10)) )

# printing letters
letters = string.ascii_letters
print ( ''.join(random.choice(letters) for i in range(10)) )

# printing digits
letters = string.digits
print ( ''.join(random.choice(letters) for i in range(10)) )

# printing punctuation
letters = string.punctuation
print ( ''.join(random.choice(letters) for i in range(10)) )

uoxzxankaa
APMUGWOMNV
eVuvmEBrZd
2748581605
{-;<,]_\}@


In [6]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [7]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [12]:
my_dict = {"color": "red", "width": 17, "height": 19}
value_to_find = "red"
for key, value in my_dict.items():
    if value == value_to_find:
        print(f'{key}: {value}')

color: red
